# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PromiseKitSandbox' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "PromiseKit", "~> 6.8"

  # Pods for PromiseKitSandbox

  target 'PromiseKitSandboxTests' do
    # Pods for testing
  end

end
